version: 0.2

eb_codebuild_settings:
  codeBuildServiceRole: arn:aws:iam::626690050115:role/service-role/AWSCodeBuildServiceRole
  image: aws/codebuild/standard:5.0
  computeType: BUILD_GENERAL1_SMALL

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt

  build:
    commands:
      - echo "Build started on $(date)"
      - python manage.py collectstatic --noinput
      - zip -r django-app.zip * .[^.]*

  post_build:
    commands:
      - echo "Running Django migrations..."
      - python manage.py migrate

artifacts:
  files:
    - django-app.zip
  discard-paths: yes
