# version: '3.6'
# services:
  # web:
  #   build:
  #     context: .
  #   command: sh -c "python manage.py migrate &&
  #                   gunicorn cocktaildb.wsgi:application --bind 0.0.0.0:8000" 
  #   volumes: 
  #     - static_volume:/home/app/code/static
  #   env_file: 
  #     - .env
  #   image: web
  #   restart: "on-failure"
  # nginx:
  #   build: 
  #     context: ./nginx
  #   ports: 
  #   - 80:80 
  #   volumes:  
  #     - static_volume:/home/app/code/static 
  #   depends_on:
  #     - web 

# volumes:
#   static_volume: