services:
  web:
    build: .
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env  # Loads environment variables from .env file
    depends_on: [] # left empty since we're using an external AWS RDS database
