# Generated by Django 5.0.7 on 2024-08-06 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('alcoholic', models.CharField(max_length=10)),
                ('glass', models.CharField(max_length=100)),
                ('instructions', models.TextField()),
                ('image_url', models.URLField()),
            ],
        ),
    ]
