# Generated by Django 4.0 on 2024-08-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drink',
            old_name='image_url',
            new_name='thumbnail',
        ),
        migrations.AddField(
            model_name='drink',
            name='ingredients',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='drink',
            name='alcoholic',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='drink',
            name='category',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='drink',
            name='glass',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='drink',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='drink',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
