# Generated by Django 4.1.7 on 2023-03-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink', models.CharField(max_length=100)),
                ('DrinkAlternate', models.CharField(max_length=100, null=True)),
                ('Tags', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('IBA', models.CharField(blank=True, max_length=100, null=True)),
                ('alcoholic', models.CharField(choices=[('Alcoholic', 'Alcoholic'), ('Non-Alcoholic', 'Non-Alcoholic')], max_length=16, null=True)),
                ('glass', models.CharField(max_length=50, null=True)),
                ('instructions', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='cocktail_images')),
                ('Ingredient1', models.CharField(max_length=50)),
                ('Ingredient2', models.CharField(max_length=50)),
                ('Ingredient3', models.CharField(max_length=50, null=True)),
                ('Ingredient4', models.CharField(max_length=50, null=True)),
                ('Ingredient5', models.CharField(max_length=50, null=True)),
                ('Ingredient6', models.CharField(max_length=50, null=True)),
                ('Ingredient7', models.CharField(max_length=50, null=True)),
                ('Ingredient8', models.CharField(max_length=50, null=True)),
                ('Ingredient9', models.CharField(max_length=50, null=True)),
                ('Ingredient10', models.CharField(max_length=50, null=True)),
                ('Measure1', models.CharField(max_length=50, null=True)),
                ('Measure2', models.CharField(max_length=50, null=True)),
                ('Measure3', models.CharField(max_length=50, null=True)),
                ('Measure4', models.CharField(max_length=50, null=True)),
                ('Measure5', models.CharField(max_length=50, null=True)),
                ('Measure6', models.CharField(max_length=50, null=True)),
                ('Measure7', models.CharField(max_length=50, null=True)),
                ('Measure8', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
