name: CI/CD for CocktailDB

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Install Elastic Beanstalk CLI
        run: |
          pip install awsebcli --upgrade  # Ensures EB CLI is available

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Initialize Elastic Beanstalk
        run: |
          eb init cocktaildb --region eu-west-2 --platform "Docker running on 64bit Amazon Linux"

      - name: Deploy to Elastic Beanstalk
        run: |
          eb deploy
