name: CI/CD for CocktailDB

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Use v4 for checkout for latest features/fixes

      - name: Set up Python
        uses: actions/setup-python@v5 # Use v5 for setup-python for latest features/fixes
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip # Ensure pip is up-to-date
          pip install -r requirements.txt
          # If your Django app needs psycopg2 or other packages, ensure they are in requirements.txt

      # --- NEW / MODIFIED DEPLOYMENT STEPS ---

      - name: Get current timestamp
        id: current-time
        uses: gerred/actions/current-time@master
        with:
          format: "YYYY-MM-DD-HH-mm-ss" # Generates a unique timestamp for the version label

      - name: Generate deployment package
        run: |
          # Create the ZIP file that Elastic Beanstalk will deploy
          # Ensure .ebextensions/ and your Django project files are included.
          zip -r deploy.zip . -x "*.git*" "node_modules/*" "*.github*" # Exclude unnecessary files/folders
          ls -l deploy.zip # Verify the zip file is created

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v22 # This is the action that handles the deployment
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: CocktailDB # <--- This should be your Elastic Beanstalk Application Name
          environment_name: cocktail-env2 # <--- This should be your Elastic Beanstalk Environment Name
          region: us-west-2 # Use the region you've defined
          version_label: "cocktaildb-env-${{ github.sha }}-${{ steps.current-time.outputs.formattedTime }}" # Unique version label
          deployment_package: deploy.zip # The ZIP file you created earlier
          wait_for_deployment: true # Important: waits for the deployment to finish
          # Optional: You can specify platform (e.g., '64bit Amazon Linux 2') if needed,
          # but typically if the environment already exists, it's not required here.
          # platform_arn: arn:aws:elasticbeanstalk:us-west-2::platform/Docker running on 64bit Amazon Linux 2/3.0.0